import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNotNull;
import static org.junit.Assert.assertTrue;
import org.junit.Test;

import java.util.HashMap;

public class HuffmanTest {

	@Test
	public void testHuffman() throws Exception {
		HashMap<String, Integer> items = new HashMap<>();
		HashMap<String, String> codes = new HashMap<>();

		items.put("a", 5);
		items.put("b", 9);
		items.put("c", 12);
		items.put("d", 13);
		items.put("e", 16);
		items.put("f", 45);

		// Build the Huffman tree
		HuffmanBuilder.buildTree(items);
		assertNotNull(HuffmanBuilder.head); // Check if the tree is not null

		// Populate the codes HashMap with the codes generated by the Huffman tree
		collectCodes(HuffmanBuilder.head, "", codes);

		// Test the Huffman Encoding
		assertEquals("0", codes.get("f"));
		assertEquals("100", codes.get("c"));
		assertEquals("101", codes.get("d"));
		assertEquals("1100", codes.get("a"));
		assertEquals("1101", codes.get("b"));
		assertEquals("111", codes.get("e"));
	}

	/**
	 * Recursively traverses the Huffman tree to collect the codes for each leaf
	 * node.
	 * 
	 * @param node  The current node being visited in the tree.
	 * @param code  The path taken as a binary string to reach the current node.
	 * @param codes The map where the character's Huffman code will be stored.
	 */
	private void collectCodes(Node node, String code, HashMap<String, String> codes) {
		// Base case: if the current node is null, just return.
		if (node == null)
			return;

		if (node.left() == null && node.right() == null) {
			// reached a leaf node, store the character and its code in the map
			codes.put(node.getName(), code);
		}

		// Traverse the left subtree by appending '0' to the code.
		collectCodes(node.left(), code + "0", codes);
		// Traverse the right subtree by appending '1' to the code.
		collectCodes(node.right(), code + "1", codes);
	}

}
